global:
  scrape_interval:     120s
  evaluation_interval: 120s

scrape_configs:
  - job_name: 'goal-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['goal-service:8080']

  - job_name: 'test-service'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['test-service:8085']
